import { useEffect } from "react";
import { Header } from "@/components/layout/Header";

const ShopifyIntegration = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const features = [
    {
      title: "Automated Product Seeding",
      description: "Automatically send products to influencers and track shipments",
      icon: "📦"
    },
    {
      title: "Sales Attribution",
      description: "Track sales generated by each influencer with unique discount codes",
      icon: "💰"
    },
    {
      title: "Inventory Sync",
      description: "Real-time inventory updates to prevent overselling",
      icon: "📊"
    },
    {
      title: "Customer Data Integration",
      description: "Sync customer data for better audience targeting",
      icon: "👥"
    }
  ];

  const steps = [
    {
      step: "1",
      title: "Install the App",
      description: "Install our Shopify app from the Shopify App Store"
    },
    {
      step: "2",
      title: "Connect Your Store",
      description: "Authorize the connection between your Shopify store and our platform"
    },
    {
      step: "3",
      title: "Configure Settings",
      description: "Set up product catalogs, shipping preferences, and tracking codes"
    },
    {
      step: "4",
      title: "Start Campaigns",
      description: "Launch influencer campaigns with automated product fulfillment"
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-slate-100">
      <Header />
      <main className="py-12 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
        <section className="text-center mb-16">
          <h1 className="text-5xl font-bold text-gray-900 mb-6">Shopify Integration</h1>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Seamlessly connect your Shopify store with our influencer marketing platform for automated product seeding, sales tracking, and inventory management.
          </p>
        </section>

        <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mb-16">
          {features.map((feature, index) => (
            <div key={index} className="bg-white p-6 rounded-xl shadow-lg text-center">
              <div className="text-4xl mb-4">{feature.icon}</div>
              <h3 className="text-lg font-semibold mb-2 text-gray-900">{feature.title}</h3>
              <p className="text-gray-600 text-sm">{feature.description}</p>
            </div>
          ))}
        </section>

        <section className="mb-16">
          <h2 className="text-3xl font-bold text-gray-900 mb-8 text-center">Easy Setup Process</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {steps.map((step, index) => (
              <div key={index} className="bg-white p-6 rounded-xl shadow-lg relative">
                <div className="absolute -top-3 -left-3 bg-green-600 text-white rounded-full w-8 h-8 flex items-center justify-center font-bold">
                  {step.step}
                </div>
                <h3 className="text-lg font-semibold mb-2 text-gray-900 mt-4">{step.title}</h3>
                <p className="text-gray-600 text-sm">{step.description}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="bg-gray-700 rounded-2xl p-8 text-white text-center">
          <h2 className="text-3xl font-bold mb-4">Ready to Connect Your Store?</h2>
          <p className="text-gray-300 mb-6">
            Start automating your influencer marketing with seamless Shopify integration.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <button className="bg-green-600 text-white px-8 py-3 rounded-lg hover:bg-green-700 transition font-semibold">
              Install Shopify App
            </button>
            <button className="border border-white text-white px-8 py-3 rounded-lg hover:bg-white hover:text-gray-700 transition">
              View Documentation
            </button>
          </div>
        </section>
      </main>
    </div>
  );
};

export default ShopifyIntegration;